# Generated by Django 5.2.12 on 2026-03-10 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50, verbose_name='Resource Type')),
                ('resource_id', models.CharField(max_length=100, verbose_name='Resource ID')),
                ('django_data', models.JSONField(verbose_name='Django Data')),
                ('odoo_data', models.JSONField(verbose_name='Odoo Data')),
                ('conflict_fields', models.JSONField(default=list, verbose_name='Conflicting Fields')),
                ('django_modified_at', models.DateTimeField(verbose_name='Django Modified At')),
                ('odoo_modified_at', models.DateTimeField(verbose_name='Odoo Modified At')),
                ('resolution', models.CharField(choices=[('pending', 'Pending Resolution'), ('use_django', 'Use Django Version'), ('use_odoo', 'Use Odoo Version'), ('merged', 'Manually Merged')], default='pending', max_length=20, verbose_name='Resolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='Resolved By')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('loan_created', 'Loan Created'), ('loan_updated', 'Loan Updated'), ('loan_status_changed', 'Loan Status Changed'), ('document_created', 'Document Created'), ('collateral_created', 'Collateral Created'), ('guarantor_created', 'Guarantor Created'), ('user_created', 'User Created'), ('odoo_loan_updated', 'Odoo Loan Updated'), ('odoo_status_changed', 'Odoo Status Changed'), ('odoo_disbursed', 'Odoo Disbursed'), ('odoo_repayment_recorded', 'Odoo Repayment Recorded')], max_length=50, verbose_name='Event Type')),
                ('direction', models.CharField(choices=[('django_to_odoo', 'Django to Odoo'), ('odoo_to_django', 'Odoo to Django')], max_length=20, verbose_name='Direction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20, verbose_name='Status')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response Data')),
                ('loan_application_id', models.UUIDField(blank=True, null=True, verbose_name='Loan Application ID')),
                ('odoo_record_id', models.IntegerField(blank=True, null=True, verbose_name='Odoo Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Retry At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('error_traceback', models.TextField(blank=True, verbose_name='Error Traceback')),
                ('source_timestamp', models.DateTimeField(blank=True, help_text='When the change was made in the source system', null=True, verbose_name='Source Timestamp')),
                ('target_timestamp', models.DateTimeField(blank=True, help_text='When the change was applied in the target system', null=True, verbose_name='Target Timestamp')),
                ('webhook_signature', models.CharField(blank=True, max_length=64, verbose_name='Webhook Signature')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='Signature Verified')),
            ],
            options={
                'verbose_name': 'Sync Event',
                'verbose_name_plural': 'Sync Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sync_syncev_status_ff017c_idx'), models.Index(fields=['event_type', 'direction'], name='sync_syncev_event_t_c7ffd2_idx'), models.Index(fields=['loan_application_id'], name='sync_syncev_loan_ap_85c342_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lock_type', models.CharField(choices=[('loan_application', 'Loan Application'), ('document', 'Document'), ('collateral', 'Collateral'), ('guarantor', 'Guarantor'), ('user', 'User')], max_length=30, verbose_name='Lock Type')),
                ('resource_id', models.CharField(max_length=100, verbose_name='Resource ID')),
                ('locked_by', models.CharField(help_text='Process or task that holds the lock', max_length=100, verbose_name='Locked By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_released', models.BooleanField(default=False, verbose_name='Released')),
            ],
            options={
                'verbose_name': 'Sync Lock',
                'verbose_name_plural': 'Sync Locks',
                'indexes': [models.Index(fields=['lock_type', 'resource_id'], name='sync_synclo_lock_ty_d836ff_idx'), models.Index(fields=['expires_at'], name='sync_synclo_expires_ec665d_idx')],
                'unique_together': {('lock_type', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('loan.created', 'Loan Created'), ('loan.updated', 'Loan Updated'), ('loan.status.changed', 'Loan Status Changed'), ('loan.approved', 'Loan Approved'), ('loan.rejected', 'Loan Rejected'), ('loan.disbursed', 'Loan Disbursed'), ('repayment.recorded', 'Repayment Recorded'), ('user.created', 'User Created')], max_length=50, verbose_name='Event')),
                ('webhook_url', models.URLField(max_length=500, verbose_name='Webhook URL')),
                ('secret_key', models.CharField(editable=False, help_text='Key used to sign webhook payloads', max_length=64, verbose_name='Secret Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered At')),
                ('total_triggers', models.IntegerField(default=0, verbose_name='Total Triggers')),
                ('successful_triggers', models.IntegerField(default=0, verbose_name='Successful Triggers')),
                ('failed_triggers', models.IntegerField(default=0, verbose_name='Failed Triggers')),
                ('custom_headers', models.JSONField(blank=True, default=dict, verbose_name='Custom Headers')),
            ],
            options={
                'verbose_name': 'Webhook Subscription',
                'verbose_name_plural': 'Webhook Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'webhook_url')},
            },
        ),
    ]
