# Generated by Django 5.2.12 on 2026-03-09 11:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Reference Number')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))], verbose_name='Loan Amount (KES)')),
                ('loan_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Loan Duration (Months)')),
                ('loan_purpose', models.TextField(blank=True, verbose_name='Loan Purpose')),
                ('interest_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Interest Rate (%)')),
                ('monthly_repayment', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monthly Repayment (KES)')),
                ('total_repayable', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Repayable (KES)')),
                ('legal_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Legal Fee (KES)')),
                ('collateral_required', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Required Collateral Value (KES)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='Disbursed At')),
                ('kyc_verified', models.BooleanField(default=False, verbose_name='KYC Verified')),
                ('crb_cleared', models.BooleanField(default=False, verbose_name='CRB Cleared')),
                ('odoo_application_id', models.IntegerField(blank=True, help_text='ID of the corresponding application in Odoo', null=True, verbose_name='Odoo Application ID')),
                ('portal_application_ref', models.CharField(blank=True, help_text='Reference from Django portal', max_length=100, verbose_name='Portal Application Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('property', 'Property'), ('vehicle', 'Vehicle'), ('logbook', 'Logbook'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20, verbose_name='Collateral Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimated Value (KES)')),
                ('valuation_date', models.DateField(verbose_name='Valuation Date')),
                ('location', models.TextField(blank=True, verbose_name='Location/Address')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial/Chassis Number')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Registration Number')),
                ('insurance_policy', models.CharField(blank=True, max_length=100, verbose_name='Insurance Policy Number')),
                ('valuation_document', models.FileField(blank=True, upload_to='collateral_documents/%Y/%m/', verbose_name='Valuation Document')),
                ('ownership_proof', models.FileField(blank=True, upload_to='collateral_documents/%Y/%m/', verbose_name='Ownership Proof')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Loan Collateral',
                'verbose_name_plural': 'Loan Collaterals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('id_number', models.CharField(max_length=20, verbose_name='National ID Number')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('employer_address', models.TextField(verbose_name='Employment/Business Address')),
                ('relationship_to_applicant', models.CharField(blank=True, choices=[('family', 'Family Member'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('business', 'Business Partner'), ('other', 'Other')], max_length=20, verbose_name='Relationship to Applicant')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monthly Income (KES)')),
                ('years_known', models.IntegerField(blank=True, null=True, verbose_name='Years Known')),
                ('guarantee_letter', models.FileField(upload_to='guarantor_documents/%Y/%m/', verbose_name='Guarantee Letter')),
                ('bank_statement', models.FileField(blank=True, upload_to='guarantor_documents/%Y/%m/', verbose_name='Bank Statement')),
                ('id_copy', models.FileField(upload_to='guarantor_documents/%Y/%m/', verbose_name='ID Copy')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Loan Guarantor',
                'verbose_name_plural': 'Loan Guarantors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_copy', 'ID Copy'), ('kra_pin', 'KRA PIN Certificate'), ('passport_photo', 'Passport Photo'), ('crb_clearance', 'CRB Clearance Certificate'), ('bank_statement', 'Bank Statement'), ('mpesa_statement', 'M-Pesa Statement'), ('payslip', 'Payslip'), ('guarantor_letter', 'Guarantor Letter'), ('collateral_proof', 'Collateral Proof of Ownership'), ('valuation_report', 'Valuation Report'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='loan_documents/%Y/%m/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes', verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Loan Document',
                'verbose_name_plural': 'Loan Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('loan_application', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Installment Number')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Amount (KES)')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest Amount (KES)')),
                ('total_due', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Due (KES)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount Paid (KES)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='Days Overdue')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Penalty Amount (KES)')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Repayment Schedule',
                'verbose_name_plural': 'Repayment Schedules',
                'ordering': ['due_date'],
                'unique_together': {('loan_application', 'installment_number')},
            },
        ),
    ]
