# Generated by Django 5.2.12 on 2026-03-11 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='employment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Employer name, job title, monthly income, duration', verbose_name='Employment Data'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('employed', 'Employed (Salary)'), ('self_employed', 'Self-Employed'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Loan Duration (Months)'),
        ),
    ]
